### ISSUE TITLE
Unable to build paclage for Fedora 34

### ISSUE THREAD

**Issue by edwkmho** [Unrud/init-headphone-fedora#1]
Problem with the error below 

*** ERROR: ambiguous python shebang in /usr/sbin/init-headphone: #!/usr/bin/python. Change it to python3 (or python2) explicitly.
error: Bad exit status from /var/tmp/rpm-tmp.oQRxBa (%install)

Had search internet but can't find the way to solve it. 

Please help. Thank.s

**Comment by Unrud** [comment]
We use the [AM_PATH_PYTHON](https://www.gnu.org/software/automake/manual/html_node/Python.html#index-AM_005fPATH_005fPYTHON) macro to find **python** >3.3 which unfortunately returns `/usr/bin/python` instead of `/usr/bin/python3` on Fedora.

~~As a workaround you can replace the following lines
https://github.com/Unrud/init-headphone/blob/9a0cc830a63251cdd409184b82bf1336a87d9627/configure.ac#L3-L4
with something like `AC_PATH_PROG([PYTHON], [python3])`~~

https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#py3_shebang_fix
